language: ruby
rvm:
  - 2.1.0

before_script:
  - "cp config/database.sample.yml config/database.yml"
  - "psql -c 'create role meurio SUPERUSER LOGIN;' postgres"
  - "psql -c 'create database meurio_test;' -U meurio postgres"
  - "sh -e /etc/init.d/xvfb start"

env:
  - DISPLAY=:99.0

script: "bundle exec rake db:migrate && bundle exec rake db:test:prepare && bundle exec rspec spec && bundle exec cucumber"

branches:
  only:
    - master
